baseURL = 'https://weita0.github.io/'
languageCode = 'en-us'
title = "Restart | 重开"
theme = 'PaperMod'
[params]
  [params.contact]
    email = 'weitao907@gmail.com'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
